#!/bin/sh
set -eu

# Build a native-host compiler that emits 32-bit i586 code, then build musl
# for that ABI. This avoids opaque prebuilt cross-toolchain downloads.
. ./versions.conf

OUT=${OUT:-out/toolchains/x86-i586}
SYSROOT="$OUT/sysroot"
WRAP="$OUT/bin"
JOBS=${JOBS:-2}

mkdir -p "$SYSROOT" "$WRAP"
command -v gcc >/dev/null
command -v ar >/dev/null
command -v ld >/dev/null

cat > "$WRAP/i586-linux-musl-gcc" <<'EOF'
#!/bin/sh
exec gcc -m32 -march=pentium "$@"
EOF
chmod +x "$WRAP/i586-linux-musl-gcc"

# Binutils operate on ELF32 objects generated by gcc -m32.
for t in ar as ld nm objcopy objdump ranlib readelf size strings strip; do
  p=$(command -v "$t")
  ln -sf "$p" "$WRAP/i586-linux-musl-$t"
done

echo "M0 bootstrap compiler prepared in $WRAP"
echo "NOTE: this is a bootstrap path; a fully pinned GCC/binutils cross toolchain remains a qualification goal."
