#!/bin/sh
set -eu

. ./versions.conf

OUT=${OUT:-out/m68k-coldfire-v2/minimal}
JOBS=${JOBS:-2}
TC=${TC:-out/toolchains/m68k-coldfire-v2/toolchain}
TC="$(cd "$TC" && pwd)"
CROSS="$TC/bin/m68k-linux-uclibc-"
OUT="$(mkdir -p "$OUT" && cd "$OUT" && pwd)"
WORK="$OUT/work"

test -x "${CROSS}gcc" || { echo "ColdFire toolchain missing: ${CROSS}gcc" >&2; exit 1; }
test -f "sources/linux-$LINUX_VERSION.tar.xz" || { echo "missing pinned Linux source; run fetch-sources.sh" >&2; exit 1; }

rm -rf "$WORK/linux"
mkdir -p "$WORK/linux" "$OUT/boot"
tar -xJf "sources/linux-$LINUX_VERSION.tar.xz" -C "$WORK/linux" --strip-components=1

make -C "$WORK/linux" ARCH=m68k CROSS_COMPILE="$CROSS" m5208evb_defconfig
grep -q '^# CONFIG_MMU is not set$' "$WORK/linux/.config" || { echo "MCF5208 kernel unexpectedly enables MMU" >&2; exit 1; }
grep -q '^CONFIG_BINFMT_FLAT=y$' "$WORK/linux/.config" || { echo "MCF5208 kernel lacks FLAT binary support" >&2; exit 1; }
grep -q '^CONFIG_SERIAL_MCF_CONSOLE=y$' "$WORK/linux/.config" || { echo "MCF5208 kernel lacks serial console" >&2; exit 1; }

make -C "$WORK/linux" -j"$JOBS" ARCH=m68k CROSS_COMPILE="$CROSS" vmlinux
cp "$WORK/linux/vmlinux" "$OUT/boot/vmlinux"
printf '#include <unistd.h>\nint main(void) { static const char msg[] = "MikrOS ColdFire V2\\n"; return write(1, msg, sizeof(msg)-1) < 0; }\n' > "$OUT/hello.c"
"${CROSS}gcc" -mcpu=5208 -Os -static "$OUT/hello.c" -o "$OUT/boot/hello"
file "$OUT/boot/hello" | tee "$OUT/boot/hello.file"
grep -q 'BFLT executable' "$OUT/boot/hello.file" || { echo "ColdFire userspace probe is not BFLT" >&2; exit 1; }
# Qualify a minimal BusyBox for the no-MMU FLAT ABI.
mkdir -p "$WORK/busybox" "$OUT/rootfs"
tar -xjf "sources/busybox-$BUSYBOX_VERSION.tar.bz2" -C "$WORK/busybox" --strip-components=1
make -C "$WORK/busybox" ARCH=m68k CROSS_COMPILE="$CROSS" allnoconfig >/dev/null
bb="$WORK/busybox/.config"
for opt in STATIC HUSH CAT ECHO LS MOUNT; do
    sed -i "s/^# CONFIG_$opt is not set$/CONFIG_$opt=y/" "$bb"
done
sed -i "s/^# CONFIG_LFS is not set$/CONFIG_LFS=y/" "$bb"
# BusyBox defaults can select ash via the shell-choice dependency even with hush enabled.
sed -i "s/^CONFIG_ASH=y$/# CONFIG_ASH is not set/" "$bb"
sed -i "s/^CONFIG_SH_IS_ASH=y$/# CONFIG_SH_IS_ASH is not set/" "$bb"
sed -i "s/^# CONFIG_SH_IS_HUSH is not set$/CONFIG_SH_IS_HUSH=y/" "$bb"
make -C "$WORK/busybox" ARCH=m68k CROSS_COMPILE="$CROSS" oldconfig </dev/null >/dev/null
grep -q "^CONFIG_SH_IS_HUSH=y$" "$bb" || { echo "BusyBox /bin/sh must use hush" >&2; exit 1; }
grep -q "^# CONFIG_SH_IS_ASH is not set$" "$bb" || { echo "BusyBox /bin/sh must not use ash" >&2; exit 1; }
grep -q "^# CONFIG_ASH is not set$" "$bb" || { echo "BusyBox ash must be disabled on no-MMU" >&2; exit 1; }
# BusyBox build reads include/config/auto.conf generated by syncconfig, not only .config.
make -C "$WORK/busybox" ARCH=m68k CROSS_COMPILE="$CROSS" prepare >/dev/null
if grep -q "^CONFIG_ASH=y$" "$WORK/busybox/include/config/auto.conf"; then
    echo "BusyBox generated configuration unexpectedly enables ash" >&2
    exit 1
fi
grep -q "^CONFIG_LFS=y$" "$bb" || { echo "BusyBox LFS must be enabled for 64-bit off_t" >&2; exit 1; }
for opt in STATIC HUSH CAT ECHO LS MOUNT; do
    grep -q "^CONFIG_$opt=y$" "$bb" || { echo "BusyBox missing $opt" >&2; exit 1; }
done
# ABI diagnostic: fail early with concrete type widths, not a BusyBox typedef guess.
cat > "$OUT/offt-probe.c" <<'EOF'
#include <sys/types.h>
typedef char check_off_t[(sizeof(off_t) == 8) ? 1 : -1];
int main(void) { return sizeof(off_t); }
EOF
"${CROSS}gcc" -mcpu=5208 -c "$OUT/offt-probe.c" -o "$OUT/offt-probe.o"
echo "BusyBox shell configuration diagnostics:"
grep -E '^(# )?CONFIG_(ASH|HUSH|SH_IS_ASH|SH_IS_HUSH)' "$bb" || true
grep -E '^(# )?CONFIG_(ASH|HUSH|SH_IS_ASH|SH_IS_HUSH)' "$WORK/busybox/include/config/auto.conf" || true
grep -E '^#define CONFIG_(ASH|HUSH)|^#define ENABLE_(ASH|HUSH)' "$WORK/busybox/include/autoconf.h" || true
sed -n '1,100p' "$WORK/busybox/shell/Makefile" || true
printf 'BusyBox LFS setting (64-bit off_t): '
grep '^CONFIG_LFS=y$' "$bb"
make -C "$WORK/busybox" -j"$JOBS" ARCH=m68k CROSS_COMPILE="$CROSS" CFLAGS_busybox="-mcpu=5208" SKIP_STRIP=y V=1
make -C "$WORK/busybox" ARCH=m68k CROSS_COMPILE="$CROSS" CONFIG_PREFIX="$OUT/rootfs" SKIP_STRIP=y install
# BusyBox installs /bin/sh itself; verify the link instead of overwriting it.
test -L "$OUT/rootfs/bin/sh" || { echo "BusyBox did not install /bin/sh" >&2; exit 1; }
file "$OUT/rootfs/bin/busybox" | tee "$OUT/boot/busybox.file"
grep -q 'BFLT executable' "$OUT/boot/busybox.file" || { echo "BusyBox is not BFLT" >&2; exit 1; }
# Stage a minimal rootfs tree for subsequent ROMFS/QEMU qualification.
mkdir -p "$OUT/rootfs/dev" "$OUT/rootfs/proc" "$OUT/rootfs/sys" "$OUT/rootfs/tmp"
cat > "$OUT/rootfs/init" <<'EOF'
#!/bin/sh
echo "MikrOS ColdFire V2 userspace started"
/bin/busybox echo "BusyBox echo: OK" || exit 1
/bin/busybox ls /bin >/dev/null || exit 1
/bin/busybox mount -t proc proc /proc || exit 1
/bin/busybox cat /proc/version >/dev/null || exit 1
echo "MikrOS ColdFire V2 procfs: PASS"
/bin/busybox mount -t sysfs sysfs /sys || exit 1
/bin/busybox ls /sys/kernel >/dev/null || exit 1
echo "MikrOS ColdFire V2 sysfs: PASS"
echo "MikrOS ColdFire V2 smoke: PASS"
exec /bin/sh
EOF
chmod 755 "$OUT/rootfs/init"
test -x "$OUT/rootfs/bin/busybox" || exit 1
test -x "$OUT/rootfs/init" || exit 1
# Package the minimal rootfs as ROMFS for the MCF5208 MTD-root profile.
command -v genromfs >/dev/null 2>&1 || { echo "genromfs is required" >&2; exit 1; }
genromfs -f "$OUT/boot/rootfs.romfs" -d "$OUT/rootfs" -V MIKROS
file "$OUT/boot/rootfs.romfs"
sha256sum "$OUT/boot/rootfs.romfs" > "$OUT/boot/rootfs.romfs.sha256"
# Build a reproducible initramfs archive as the next boot-test input.
command -v cpio >/dev/null 2>&1 || { echo "cpio is required" >&2; exit 1; }
# fakeroot lets CI create device nodes in the archive without root privileges.
command -v fakeroot >/dev/null 2>&1 || { echo "fakeroot is required" >&2; exit 1; }
fakeroot sh -c '
  set -eu
  cd "$1"
  mknod dev/console c 5 1
  chmod 600 dev/console
  mknod dev/null c 1 3
  chmod 666 dev/null
  find . -print | LC_ALL=C sort | cpio --quiet -o -H newc
' sh "$OUT/rootfs" > "$OUT/boot/rootfs.cpio"
test -s "$OUT/boot/rootfs.cpio" || { echo "empty initramfs" >&2; exit 1; }
sha256sum "$OUT/boot/rootfs.cpio" > "$OUT/boot/rootfs.cpio.sha256"
# Embed the cpio image into the no-MMU kernel and rebuild for QEMU userspace smoke.
scripts_config="$WORK/linux/scripts/config"
test -x "$scripts_config" || { echo "kernel scripts/config missing" >&2; exit 1; }
"$scripts_config" --file "$WORK/linux/.config" --set-str INITRAMFS_SOURCE "$OUT/boot/rootfs.cpio"
"$scripts_config" --file "$WORK/linux/.config" -e BLK_DEV_INITRD
"$scripts_config" --file "$WORK/linux/.config" -e SYSFS
make -C "$WORK/linux" ARCH=m68k CROSS_COMPILE="$CROSS" olddefconfig
grep -q "^CONFIG_SYSFS=y$" "$WORK/linux/.config" || { echo "ColdFire kernel lacks sysfs" >&2; exit 1; }
make -C "$WORK/linux" -j"$JOBS" ARCH=m68k CROSS_COMPILE="$CROSS" vmlinux
cp "$WORK/linux/vmlinux" "$OUT/boot/vmlinux"

file "$OUT/boot/vmlinux"
sha256sum "$OUT/boot/vmlinux" > "$OUT/boot/vmlinux.sha256"
echo "built MCF5208 no-MMU kernel"
